services:
    # FileCreator
    AppoloDev\SFToolboxBundle\Maker\FileCreator\EntityFileCreator:
        arguments:
            - '%kernel.project_dir%'
    AppoloDev\SFToolboxBundle\Maker\FileCreator\ScaffoldFileCreator:
        arguments:
            - '%kernel.project_dir%'

    # Command
    AppoloDev\SFToolboxBundle\Maker\Command\MakeDomainEntityCommand:
        arguments:
            - '@AppoloDev\SFToolboxBundle\Maker\FileCreator\EntityFileCreator'
        tags:
            - { name: console.command }

    AppoloDev\SFToolboxBundle\Maker\Command\MakeScaffoldCommand:
        arguments:
            - '@AppoloDev\SFToolboxBundle\Maker\FileCreator\ScaffoldFileCreator'
        tags:
            - { name: console.command }