services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppoloDev\SFToolboxBundle\Security\Http\EventListener\IsNotGrantedAttributeListener:
        arguments:
            - '@security.authorization_checker'
            - '@security.is_granted_attribute_expression_language'
        tags: ['kernel.event_subscriber']

    AppoloDev\SFToolboxBundle\MessageHandler\EmailSenderHandler:
        arguments:
            - '%env(SENDER_EMAIL)%'
            - '%env(SENDER_NAME)%'
            - '@mailer'
            - '@kernel'
            - '@assets.packages'
        tags:
            - { name: messenger.message_handler, transport: async }

    # FileCreator
    AppoloDev\SFToolboxBundle\Maker\FileCreator\EntityFileCreator:
        arguments:
            - '%kernel.project_dir%'
    AppoloDev\SFToolboxBundle\Maker\FileCreator\ScaffoldFileCreator:
        arguments:
            - '%kernel.project_dir%'

    # Command
    AppoloDev\SFToolboxBundle\Maker\Command\MakeDomainEntityCommand:
        arguments:
            - '@AppoloDev\SFToolboxBundle\Maker\FileCreator\EntityFileCreator'
        tags:
            - { name: console.command }

    AppoloDev\SFToolboxBundle\Maker\Command\MakeScaffoldCommand:
        arguments:
            - '@AppoloDev\SFToolboxBundle\Maker\FileCreator\ScaffoldFileCreator'
        tags:
            - { name: console.command }

    # Twig Extension
    AppoloDev\SFToolboxBundle\Twig\:
        resource: '../../Twig/*'
        tags:
            - { name: twig.extension }

    AppoloDev\SFToolboxBundle\UI\Components\:
        resource: '../../UI/Components/*'
        tags:
            - { name: twig.component }